version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "10000:10000"
    env_file: ./backend/.env
    networks:
      - codify-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - codify-network

networks:
  codify-network:
    driver: bridge
